service: serverless-fastify

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  profile: ${opt:profile, 'default'}
  region: us-east-1
  memorySize: 512
  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-offline

functions:
  app:
    handler: src/app.api
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

package:
  exclude:
    - '**'
    - '!node_modules/**/*'
    - '!src/*'
