service: serverless-fastify

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  profile: ${opt:profile, 'prisma_demo'}
  region: us-east-2
  memorySize: 512
  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-dotenv-plugin
  - serverless-offline

functions:
  app:
    handler: src/app.api
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

package:
  exclude:
    - '**'
    - '!node_modules/**/*'
    - '!src/*'
    - '*.eslint'
    - '*.env'
    - 'node_modules/@prisma/cli/*-darwin'
    - 'node_modules/@prisma/cli/query-engine-*'
    - 'node_modules/.prisma/client/*-darwin'
    - 'node_modules/@prisma/engines/**'
